---
- name: "Configure the EKS cluster with kubectl"
  hosts: management[0]
  user: ec2-user
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  roles:
    - capstone-deployment
    - capstone-service
